[profile.dotenv]
path = ".env"

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
optimizer = true
solc = "0.8.23"
solc_version = "0.8.23"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]





[etherscan]
  sepolia = { key = "${API_KEY_ETHERSCAN}" }
  
[rpc_endpoints]
  sepolia = "https://eth-sepolia.g.alchemy.com/v2/gI5vP9Z5AOwlAlql_jAXEWdEh9Z169iz"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
